version: '3.8'
services:
  client:
    image: rafaelmoczalla/nextflow-node
    command: "sh -c 'while true; do echo alive at $$(date); sleep 180; done'"
    privileged: true
    volumes:
      - work:/work
    network_mode: default
  node:
    image: rafaelmoczalla/nextflow-node
    command: "nextflow node"
    privileged: true
    volumes:
      - work:/work
    network_mode: default
volumes:
  work:
